language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coverage
# command to run tests
script:
  - cd tests && bash coverage.bash coverage

